### ISSUE TITLE
Convert into template repo with GitHub/-Lab issues, boards, etc.

### ISSUE THREAD

**Issue by katrinleinweber** [softwaresaved/software-management-plans#12]
Does an SMP _have to be_ a document/file? Could it also be a bunch of pre-defined issues, file templates (see #9), project boards, etc.?

[GitLab added this a while ago](https://about.gitlab.com/2017/08/22/gitlab-9-5-released/#project-templates), [GitHub followed recently](https://blog.github.com/2018-05-01-creating-new-boards-with-project-templates/). Thus, the repos could be a living check-list, [ticked-off](https://help.github.com/articles/closing-issues-using-keywords/) continously as the software develops, even in a crowd-sourced manner.

Files within the template repo could additionally be evolved then, also by funders, and those updates could be merged into the project repos similar to what the Carpentries are doing with their [upstream `styles`](https://github.com/swcarpentry/styles/) and [the downstream lessons](https://github.com/swcarpentry/r-novice-inflammation/pull/350). [GitLab is already discussing to add a copy function to issues](https://gitlab.com/gitlab-org/gitlab-ce/issues/21863).

**Comment by katrinleinweber** [comment]
More considerations (also for myself, in case I find time to do try out this idea):

- [ ] try on GitHub first, GitLab [GitLab's templates seem rather focussed on technical details, not project management](https://gitlab.com/gitlab-org/project-templates)
- [ ] test whether project board within a repo are [imported](https://github.com/new/import)
    - if not: use org-level project board & [promote copying](https://help.github.com/articles/copying-a-project-board/)
- [ ] start with high-level issues (1 per [`question`](https://github.com/softwaresaved/software-management-plans/blob/master/SMP_Checklist.yaml) & copy `consider`ations, etc. as `- [ ]` tasks)
- [ ] turn `sections` into [labels](https://help.github.com/articles/about-labels/)

**Comment by katrinleinweber** [comment]
[GitHub's repo importer](https://github.com/new/import) ignores issues :-/

**Comment by katrinleinweber** [comment]
During working on the [prototype `GitLab.com/KatrinLeinweber/SMP-evo`](https://gitlab.com/katrinleinweber/SMP-evo), I think the more simple version discussed in #9 is better, until there may be a way to auto-generate issues from the [`SMP_Checklist.yaml`](https://github.com/softwaresaved/software-management-plans/blob/master/SMP_Checklist.yaml).

**Comment by katrinleinweber** [comment]
Note to self: using existing tools like [gitlab-copy](https://github.com/gotsunami/gitlab-copy) or [gitlab2github](https://github.com/rbsdev/gitlab2github) is hindered by those needing both GitHub & GitLab tokens. Thus, they may be useful for people migrating their own repos/projects/issues, but not for publishing a template repo that other people can use as-is.

**Comment by katrinleinweber** [comment]
GitLab released the [project](https://about.gitlab.com/2018/08/22/gitlab-11-2-released/#custom-project-templates-on-the-instance-level) & [file](https://about.gitlab.com/2018/09/22/gitlab-11-3-released/#custom-file-templates-for-self-managed-instances) templates features in Aug. & Sept. 2018, but both custom variants are currently limited to the two most expensive tiers.

**Comment by geyslein** [comment]
Any news @mikej888 regarding a new feature implementing SMP templates? I definitely see the usefulness for my institution's software projects. Same for #22

**Comment by mikej888** [comment]
@geyslein: @katrinleinweber was driving that activity. I'm not working on SMPs myself now (as I've moved on from The Software Sustainability Institute) but my colleagues @shoaibsufi @gperu might be able to comment on future plans relating to SMPs.

**Comment by katrinleinweber** [comment]
I'm not working on this any more, either, I'm sorry. It seems to me that the currently most mature approach is https://emilyriederer.github.io/projmgr/articles/building-custom-plans.html

**Comment by katrinleinweber** [comment]
Having stumbled upon https://about.gitlab.com/handbook/marketing/product-marketing/getting-started/104/ today, I guess _that spreadsheet-base process_ is simplest. Also, if people want to fill out the SMP not in GitLab, the spreadsheet just needs a few more rows for their entries.
