### ISSUE TITLE
convert into file template

### ISSUE THREAD

**Issue by katrinleinweber** [softwaresaved/software-management-plans#9]
[GitLab seems to be implementing "custom file templates"](https://gitlab.com/gitlab-org/gitlab-ce/issues/26199). Might it be useful to offer this list of questions in the same format as for example [issue or PR templates](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/.gitlab)?

So that GitLab admins can load it into their instances to allow their users to load your software management plan into their repos and fill them out in Markdown.  That way, the plan would be documented within the repo and could be updated in the same way as other docu.

**Comment by mikej888** [comment]
@katrinleinweber thanks for the suggestion. I was today going ping my colleagues about what we might do with the software management content to make it easier to use and this seems to be a good option that could be explored!

**Comment by katrinleinweber** [comment]
On second thought, it could also be an issue template, because it could be introduced to a software project's repo that way as well.

**Comment by mikej888** [comment]
See also sample MarkDown-style checklist, https://gist.github.com/marioa/70c791c7ec098b167aafb6916cc79569

**Comment by mikej888** [comment]
Done at commit: ee1b6de67ab3e6e5d1e6004a4e8fcdedb9b4ed95.
